eureka:
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone : http://localhost:8761/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true